import React from "react";
import { render, act } from "@testing-library/react";
import Home from "../pages/Home";
import { BrowserRouter } from "react-router-dom";
import {
  fetchTopRatedMovies,
  fetchPopularMovies,
  fetchReviewMovie,
} from "../api/movieApi";

test("renders Home component", async () => {
  fetchTopRatedMovies.mockResolvedValue([
    {
      adult: false,
      backdrop_path: "/tmU7GeKVybMWFButWEGl2M4GeiP.jpg",
      genre_ids: [18, 80],
      id: 238,
      original_language: "en",
      original_title: "The Godfather",
      overview:
        "Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.",
      popularity: 132.858,
      poster_path: "/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
      release_date: "1972-03-14",
      title: "The Godfather",
      video: false,
      vote_average: 8.7,
      vote_count: 18256,
    },
    {
      adult: false,
      backdrop_path: "/kXfqcdQKsToO0OUXHcrrNCHDBzO.jpg",
      genre_ids: [18, 80],
      id: 278,
      original_language: "en",
      original_title: "The Shawshank Redemption",
      overview:
        "Framed in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.",
      popularity: 97.132,
      poster_path: "/lyQBXzOQSuE59IsHyhrp0qIiPAz.jpg",
      release_date: "1994-09-23",
      title: "The Shawshank Redemption",
      video: false,
      vote_average: 8.7,
      vote_count: 24149,
    },
    {
      adult: false,
      backdrop_path: "/kGzFbGhp99zva6oZODW5atUtnqi.jpg",
      genre_ids: [18, 80],
      id: 240,
      original_language: "en",
      original_title: "The Godfather Part II",
      overview:
        "In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.",
      popularity: 69.161,
      poster_path: "/bMadFzhjy9T7R8J48QGq1ngWNAK.jpg",
      release_date: "1974-12-20",
      title: "The Godfather Part II",
      video: false,
      vote_average: 8.6,
      vote_count: 11017,
    },
    {
      adult: false,
      backdrop_path: "/zb6fM1CX41D9rF9hdgclu0peUmy.jpg",
      genre_ids: [18, 36, 10752],
      id: 424,
      original_language: "en",
      original_title: "Schindler's List",
      overview:
        "The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.",
      popularity: 59.413,
      poster_path: "/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg",
      release_date: "1993-12-15",
      title: "Schindler's List",
      video: false,
      vote_average: 8.6,
      vote_count: 14273,
    },
    {
      adult: false,
      backdrop_path: "/vI3aUGTuRRdM7J78KIdW98LdxE5.jpg",
      genre_ids: [35, 18, 10749],
      id: 19404,
      original_language: "hi",
      original_title: "दिलवाले दुल्हनिया ले जायेंगे",
      overview:
        "Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to be married to her childhood fiancé. Raj leaves for India with a mission at his hands, to claim his lady love under the noses of her whole family. Thus begins a saga.",
      popularity: 34.699,
      poster_path: "/ktejodbcdCPXbMMdnpI9BUxW6O8.jpg",
      release_date: "1995-10-20",
      title: "Dilwale Dulhania Le Jayenge",
      video: false,
      vote_average: 8.6,
      vote_count: 4177,
    },
    {
      adult: false,
      backdrop_path: "/mSDsSDwaP3E7dEfUPWy4J0djt4O.jpg",
      genre_ids: [16, 10751, 14],
      id: 129,
      original_language: "ja",
      original_title: "千と千尋の神隠し",
      overview:
        "A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.",
      popularity: 86.026,
      poster_path: "/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg",
      release_date: "2001-07-20",
      title: "Spirited Away",
      video: false,
      vote_average: 8.5,
      vote_count: 14555,
    },
    {
      adult: false,
      backdrop_path: "/qqHQsStV6exghCM7zbObuYBiYxw.jpg",
      genre_ids: [18],
      id: 389,
      original_language: "en",
      original_title: "12 Angry Men",
      overview:
        "The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case soon becomes a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other.",
      popularity: 53.31,
      poster_path: "/ow3wq89wM8qd5X7hWKxiRfsFf9C.jpg",
      release_date: "1957-04-10",
      title: "12 Angry Men",
      video: false,
      vote_average: 8.5,
      vote_count: 7424,
    },
    {
      adult: false,
      backdrop_path: "/dIWwZW7dJJtqC6CgWzYkNVKIUm8.jpg",
      genre_ids: [10749, 16, 18],
      id: 372058,
      original_language: "ja",
      original_title: "君の名は。",
      overview:
        "High schoolers Mitsuha and Taki are complete strangers living separate lives. But one night, they suddenly switch places. Mitsuha wakes up in Taki’s body, and he in hers. This bizarre occurrence continues to happen randomly, and the two must adjust their lives around each other.",
      popularity: 79.652,
      poster_path: "/q719jXXEzOoYaps6babgKnONONX.jpg",
      release_date: "2016-08-26",
      title: "Your Name.",
      video: false,
      vote_average: 8.5,
      vote_count: 10043,
    },
    {
      adult: false,
      backdrop_path: "/hiKmpZMGZsrkA3cdce8a7Dpos1j.jpg",
      genre_ids: [35, 53, 18],
      id: 496243,
      original_language: "ko",
      original_title: "기생충",
      overview:
        "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
      popularity: 75.233,
      poster_path: "/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
      release_date: "2019-05-30",
      title: "Parasite",
      video: false,
      vote_average: 8.5,
      vote_count: 16015,
    },
    {
      adult: false,
      backdrop_path: "/4HodYYKEIsGOdinkGi2Ucz6X9i0.jpg",
      genre_ids: [28, 12, 16, 878],
      id: 569094,
      original_language: "en",
      original_title: "Spider-Man: Across the Spider-Verse",
      overview:
        "After reuniting with Gwen Stacy, Brooklyn’s full-time, friendly neighborhood Spider-Man is catapulted across the Multiverse, where he encounters the Spider Society, a team of Spider-People charged with protecting the Multiverse’s very existence. But when the heroes clash on how to handle a new threat, Miles finds himself pitted against the other Spiders and must set out on his own to save those he loves most.",
      popularity: 1166.035,
      poster_path: "/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg",
      release_date: "2023-05-31",
      title: "Spider-Man: Across the Spider-Verse",
      video: false,
      vote_average: 8.5,
      vote_count: 2358,
    },
    {
      adult: false,
      backdrop_path: "/dqK9Hag1054tghRQSqLSfrkvQnA.jpg",
      genre_ids: [18, 28, 80, 53],
      id: 155,
      original_language: "en",
      original_title: "The Dark Knight",
      overview:
        "Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.",
      popularity: 105.592,
      poster_path: "/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
      release_date: "2008-07-14",
      title: "The Dark Knight",
      video: false,
      vote_average: 8.5,
      vote_count: 30076,
    },
    {
      adult: false,
      backdrop_path: "/l6hQWH9eDksNJNiXWYRkWqikOdu.jpg",
      genre_ids: [14, 18, 80],
      id: 497,
      original_language: "en",
      original_title: "The Green Mile",
      overview:
        "A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the cell block's head guard, Paul Edgecomb, recognizes Coffey's miraculous gift, he tries desperately to help stave off the condemned man's execution.",
      popularity: 70.699,
      poster_path: "/o0lO84GI7qrG6XFvtsPOSV7CTNa.jpg",
      release_date: "1999-12-10",
      title: "The Green Mile",
      video: false,
      vote_average: 8.5,
      vote_count: 15621,
    },
    {
      adult: false,
      backdrop_path: "/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg",
      genre_ids: [53, 80],
      id: 680,
      original_language: "en",
      original_title: "Pulp Fiction",
      overview:
        "A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.",
      popularity: 76.167,
      poster_path: "/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
      release_date: "1994-09-10",
      title: "Pulp Fiction",
      video: false,
      vote_average: 8.5,
      vote_count: 25456,
    },
    {
      adult: false,
      backdrop_path: "/qdIMHd4sEfJSckfVJfKQvisL02a.jpg",
      genre_ids: [35, 18, 10749],
      id: 13,
      original_language: "en",
      original_title: "Forrest Gump",
      overview:
        "A man with a low IQ has accomplished great things in his life and been present during significant historic events—in each case, far exceeding what anyone imagined he could do. But despite all he has achieved, his one true love eludes him.",
      popularity: 67.866,
      poster_path: "/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg",
      release_date: "1994-06-23",
      title: "Forrest Gump",
      video: false,
      vote_average: 8.5,
      vote_count: 24970,
    },
    {
      adult: false,
      backdrop_path: "/2u7zbn8EudG6kLlBzUYqP8RyFU4.jpg",
      genre_ids: [12, 14, 28],
      id: 122,
      original_language: "en",
      original_title: "The Lord of the Rings: The Return of the King",
      overview:
        "Aragorn is revealed as the heir to the ancient kings as he, Gandalf and the other members of the broken fellowship struggle to save Gondor from Sauron's forces. Meanwhile, Frodo and Sam take the ring closer to the heart of Mordor, the dark lord's realm.",
      popularity: 92.861,
      poster_path: "/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg",
      release_date: "2003-12-01",
      title: "The Lord of the Rings: The Return of the King",
      video: false,
      vote_average: 8.5,
      vote_count: 21851,
    },
    {
      adult: false,
      backdrop_path: "/eoCSp75lxatmIa6aGqfnzwtbttd.jpg",
      genre_ids: [37],
      id: 429,
      original_language: "it",
      original_title: "Il buono, il brutto, il cattivo",
      overview:
        "While the Civil War rages on between the Union and the Confederacy, three men – a quiet loner, a ruthless hitman, and a Mexican bandit – comb the American Southwest in search of a strongbox containing $200,000 in stolen gold.",
      popularity: 79.939,
      poster_path: "/bX2xnavhMYjWDoZp1VM6VnU1xwe.jpg",
      release_date: "1966-12-23",
      title: "The Good, the Bad and the Ugly",
      video: false,
      vote_average: 8.5,
      vote_count: 7536,
    },
    {
      adult: false,
      backdrop_path: "/sw7mordbZxgITU877yTpZCud90M.jpg",
      genre_ids: [18, 80],
      id: 769,
      original_language: "en",
      original_title: "GoodFellas",
      overview:
        "The true story of Henry Hill, a half-Irish, half-Sicilian Brooklyn kid who is adopted by neighbourhood gangsters at an early age and climbs the ranks of a Mafia family under the guidance of Jimmy Conway.",
      popularity: 47.208,
      poster_path: "/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg",
      release_date: "1990-09-12",
      title: "GoodFellas",
      video: false,
      vote_average: 8.5,
      vote_count: 11439,
    },
    {
      adult: false,
      backdrop_path: "/qvZ91FwMq6O47VViAr8vZNQz3WI.jpg",
      genre_ids: [28, 18],
      id: 346,
      original_language: "ja",
      original_title: "七人の侍",
      overview:
        "A samurai answers a village's request for protection after he falls on hard times. The town needs protection from bandits, so the samurai gathers six others to help him teach the people how to defend themselves, and the villagers provide the soldiers with food.",
      popularity: 32.929,
      poster_path: "/8OKmBV5BUFzmozIC3pPWKHy17kx.jpg",
      release_date: "1954-04-26",
      title: "Seven Samurai",
      video: false,
      vote_average: 8.5,
      vote_count: 3126,
    },
    {
      adult: false,
      backdrop_path: "/zoVeIgKzGJzpdG6Gwnr7iOYfIMU.jpg",
      genre_ids: [18, 10749],
      id: 11216,
      original_language: "it",
      original_title: "Nuovo Cinema Paradiso",
      overview:
        "A filmmaker recalls his childhood, when he fell in love with the movies at his village's theater and formed a deep friendship with the theater's projectionist.",
      popularity: 26.238,
      poster_path: "/8SRUfRUi6x4O68n0VCbDNRa6iGL.jpg",
      release_date: "1988-11-17",
      title: "Cinema Paradiso",
      video: false,
      vote_average: 8.5,
      vote_count: 3819,
    },
    {
      adult: false,
      backdrop_path: "/gavyCu1UaTaTNPsVaGXT6pe5u24.jpg",
      genre_ids: [35, 18],
      id: 637,
      original_language: "it",
      original_title: "La vita è bella",
      overview:
        "A touching story of an Italian book seller of Jewish ancestry who lives in his own little fairy tale. His creative and happy life would come to an abrupt halt when his entire family is deported to a concentration camp during World War II. While locked up he tries to convince his son that the whole thing is just a game.",
      popularity: 45.496,
      poster_path: "/mfnkSeeVOBVheuyn2lo4tfmOPQb.jpg",
      release_date: "1997-12-20",
      title: "Life Is Beautiful",
      video: false,
      vote_average: 8.5,
      vote_count: 12006,
    },
  ]);
  fetchPopularMovies.mockResolvedValue([
    {
      adult: false,
      backdrop_path: "/qWQSnedj0LCUjWNp9fLcMtfgadp.jpg",
      genre_ids: [28, 12, 878],
      id: 667538,
      original_language: "en",
      original_title: "Transformers: Rise of the Beasts",
      overview:
        "When a new threat capable of destroying the entire planet emerges, Optimus Prime and the Autobots must team up with a powerful faction known as the Maximals. With the fate of humanity hanging in the balance, humans Noah and Elena will do whatever it takes to help the Transformers as they engage in the ultimate battle to save Earth.",
      popularity: 7985.481,
      poster_path: "/gPbM0MK8CP8A174rmUwGsADNYKD.jpg",
      release_date: "2023-06-06",
      title: "Transformers: Rise of the Beasts",
      video: false,
      vote_average: 7.3,
      vote_count: 1479,
    },
  ]);
  const mockReviewData = [
    {
      author: "josezapata",
      author_details: {
        name: "",
        username: "josezapata",
        avatar_path: null,
        rating: null,
      },
      content:
        "Transformers is the best movie of the franchise ! \r\n\r\nTransformers took everything that worked with Bumblebee . Anthony Ramos and Dominique fishback did a great performance and pete Davinson as mirage stole the show , but the true star is the adsolute best soundtrack of the 90' . I am happy to say that transformers is a lot of fun , the cgi looks pretty good . When I first watched this movie a lot of people were clapping and they laughed a lot . In conclusion , this new transformers movie is the beginning of something much bigger ! Cant wait to see what paramount has in store for us . 9.5/10",
      created_at: "2023-06-06T08:59:11.390Z",
      id: "647ef55f93828e01337941c7",
      updated_at: "2023-06-07T14:22:40.001Z",
      url: "https://www.themoviedb.org/review/647ef55f93828e01337941c7",
    },
    {
      author: "garethmb",
      author_details: {
        name: "",
        username: "garethmb",
        avatar_path:
          "/https://secure.gravatar.com/avatar/3593437cbd05cebe0a4ee753965a8ad1.jpg",
        rating: null,
      },
      content:
        'The latest in the long-running and popular Transformer series has arrived with “Transformers: Rise of the Beasts”.  Taking a cue from the recent “Bumblebee” movie,  the movie cleverly serves not only as a prequel but as a platform to introduce a series of stories leading up to the original films.\r\n\r\nIt is learned that a planet-destroying evil is fixated on obtaining a key that will allow it to travel to any point in the universe to continue its reign of destruction. The animal-based Maximals are able to escape with the key and hide it on Earth where they will also remain in secret as guardians.\r\n\r\nFlash forward to 1994 when Noah Diaz (Anthony Ramos), following his stint in the Army is looking to find gainful employment to help his mother as well as his ailing brother.  Despite being a wizard with electronics Noah is not considered to be a team player which has hampered his job prospects and leads him to consider criminal activities in an effort to obtain much-needed funds for his brother\'s medical bills.\r\n\r\nIn a moment of desperation, Noah attempts to steal a loaded Porsche but finds he is unable to follow through on the act as it is against his moral compass.  Unknown to Noah the car is actually an Autobot named Mirage (Pete Davidson), who soon enlists Noah to help them find the key which they have recently detected.\r\n\r\nThis does not sit well with Optimus Prime (Peter Cullen), who believes that humanity will only act in your best interests and that his crew needs to find the key so that they can return to their war-ravaged, Cybertron.\r\n\r\nIt is learned that a crafty but perpetually overlooked museum intern named Elena (Dominique Fishback), has accidentally activated the key and in doing so has allowed the evil Scourge (Peter Dinklage), and his minions to zero in on its location as he attempts to obtain the key for his master and is willing to destroy all were in his way.\r\n\r\nNoah and Elena soon find themselves paired with their unexpected allies as they race to stop the evil from obtaining both parts of the key and find themselves with some unexpected allies in the form of the Maximals.\r\n\r\nWhat follows is a frantic action-adventure film that cleverly combines humor, action, dazzling visual effects, and a tail that is part Indiana Jones, and Transformers with a surprising amount of humanity.\r\n\r\nIt would be easy for the human cast the overshadowed by the massive and visually spectacular creations that frequently transform and battle it out across numerous action sequences.  However, director Steven Caple Jr. takes advantage of his young talent both of whom are clearly potential stars in the making as they provide a grounding humanity to the film which makes it more than a lavish FX showcase.\r\n\r\nThe film also has an impressive era-specific soundtrack and a scene near the end that offers up some intriguing and exciting possibilities for the future. "Transformers: Rise of the Beasts" is a highly enjoyable summer action adventure as well as one the more enjoyable films in the franchise and should delight fans of the franchise and has me for the first time in a long time eagerly awaiting what comes next.\r\n\r\n4 stars out of 5',
      created_at: "2023-06-06T14:29:14.555Z",
      id: "647f42bacf4b8b014190d724",
      updated_at: "2023-06-06T14:29:14.642Z",
      url: "https://www.themoviedb.org/review/647f42bacf4b8b014190d724",
    },
    {
      author: "Chris Sawin",
      author_details: {
        name: "Chris Sawin",
        username: "ChrisSawin",
        avatar_path:
          "/https://secure.gravatar.com/avatar/bf3b87ecb40599290d764e6d73c86319.jpg",
        rating: 2.0,
      },
      content:
        "_Transformers: Rise of the Beasts_ is a pointless entry in the live-action _Transformers_ film franchise. The Beasts Wars characters are forgettable, the attempts at humor are excruciatingly lame, Optimus Prime is a huge jerk, and the action is trash. If you were exhausted with the _Transformers_ franchise before, then _Rise of the Beasts_ will have you flatlining and succumbing to sheer and utter boredom.\r\n\r\n**Full review:** https://bit.ly/robotjerks",
      created_at: "2023-06-09T13:57:17.518Z",
      id: "64832fbde375c000c526e9ad",
      updated_at: "2023-06-09T13:57:17.620Z",
      url: "https://www.themoviedb.org/review/64832fbde375c000c526e9ad",
    },
    {
      author: "CinemaSerf",
      author_details: {
        name: "CinemaSerf",
        username: "Geronimo1967",
        avatar_path: "/1kks3YnVkpyQxzw36CObFPvhL5f.jpg",
        rating: 6.0,
      },
      content:
        'You know what - this is my favourite "Transformers" movie. Now that\'s not really saying much, most of them are pretty poor, but somehow the shamelessly derivative nature of this just made it more entertaining. It all starts with "Optimus Primal" (aka. "Kingus Kongus") having a fight with the all-consuming "Unicron" (narked because a typo robbed him of his chance to just be an horse with an horn) for a key that can open portals between worlds enabling the baddie to quite literally eat them and move on. The solution to that battle is a bit of a compromise and scoot forward hundreds of year and New Yorker "Noah" (Anthony Ramos) has a problem. His younger brother "Kris" (Dean Scott Vasquez) is very poorly and they cannot afford his medical bills. "Noah" turns to crime and that\'s where he encounters the newly invigorated "Autobots" who have realised that "Elena" (Dominique Fishback) - a researcher in a museum - has rediscovered the hidden key. They have to retrieve it before it falls into more malevolent hands. Soon the two hapless humans and their robots are engaged in a battle royal that sees the museum pretty much trashed before they head to Peru where they encounter the "Maximals" and the beautiful Inca terraces are soon for the chop too. So far I reckon we\'ve been through loads of episodes of "Stargate" as well "King Kong" (probably the Peter Jackson one), "The Goblet of Fire"; "Independence Day", "Star Trek" (JJ Abrams version), all four "Indiana Jones" films - which, to be fair are even acknowledged in the script, and the armoured eagle "Airazor" reminded me of a hairier version of "Bubo" from "Clash of the Titans". The visuals are excellent and for the most part it\'s got plenty of action but as we near the ever-so-predictable denouement the pace slackens off and cheesy sentiment brings the thing to a grinding halt a couple of times! There\'s no jeopardy at all, really, and given that "Optimus Prime" - maybe he ought to be called "Hopeless Prime" because he is pretty useless in a fight - gets to make his grand speech at the end, I\'m sure there will be more for our intrepid young "Noah" to come. Big screen essential - this will look bland and repetitive on the telly. Maybe it\'ll help sell some toys?',
      created_at: "2023-06-10T04:45:32.012Z",
      id: "6483ffebe375c000e24f07ae",
      updated_at: "2023-06-10T04:45:32.107Z",
      url: "https://www.themoviedb.org/review/6483ffebe375c000e24f07ae",
    },
    {
      author: "DAVID TILAN",
      author_details: {
        name: "DAVID TILAN",
        username: "DavidTIlanTF",
        avatar_path: "/j70nZYh286oGS1iBvxs7oD4SJse.jpg",
        rating: 10.0,
      },
      content:
        "**Just incredible**, Tstrong texthe Autobots are amazing **full of action.**",
      created_at: "2023-06-10T18:32:38.699Z",
      id: "6484c1c6c9dbf9011dfc0884",
      updated_at: "2023-06-13T15:50:07.503Z",
      url: "https://www.themoviedb.org/review/6484c1c6c9dbf9011dfc0884",
    },
    {
      author: "The Movie Mob",
      author_details: {
        name: "The Movie Mob",
        username: "mooney240",
        avatar_path: "/blEC280vq31MVaDcsWBXuGOsYnB.jpg",
        rating: 7.0,
      },
      content:
        "**Transformers: Rise of the Beasts rescues the franchise from the all-out goofy mess it had become and gives it a fun and promising new beginning.**\r\n\r\nTransformers: Rise of the Beasts recaptures some of the fun and charm of Bumblebee and the early Transformers films and blends it with the aesthetics and nostalgia of the old 80s cartoon. Rise of the Beasts establishes some decent human leads that aren’t annoying while keeping the focus on the robot conflict. The voice cast was fantastic! Peter Cullen as Optimus Prime will always be the greatest of all time. Peter Dinklage’s Scourge sounds and looks vicious. Ron Perlman, Michelle Yeoh, Pete Davidson, and Cristo Fernández provide solid performances, giving their characters a little fun and even some heart. Rise of the Beasts reels the franchise back in from the outrageous goofiness of the Wahlberg entries but still has a good time recognizing its primary audience is kids and parents who grew up on the cartoon. The intensity and pacing of the first 2 acts are superb! The final act gets a little cheesy and starts to feel generic, but it is no worse than the climax of recent Marvel films. Rise of the Beasts isn’t perfect but it sets the Transformers back on the right path.",
      created_at: "2023-07-16T23:24:54.990Z",
      id: "64b47c4623d278010731160d",
      updated_at: "2023-07-16T23:24:55.083Z",
      url: "https://www.themoviedb.org/review/64b47c4623d278010731160d",
    },
  ];
  fetchReviewMovie.mockResolvedValue(mockReviewData);
  await act(async () => {
    render(<Home />, { wrapper: BrowserRouter });
  });
});
